### ISSUE TITLE
aqemu from AUR seg fault

### ISSUE THREAD

**Issue by TheBagarius** [tobimensch/aqemu#92]
Hi,

I installed aqemu from the AUR and get these errors when I try to launch it. 

```
AQEMU Warning [2] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-arm" element!

AQEMU Warning [3] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-cris" element!

AQEMU Warning [4] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-m68k" element!

AQEMU Warning [5] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-microblaze" element!

AQEMU Warning [6] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-mips" element!

AQEMU Warning [7] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-mips64" element!

AQEMU Warning [8] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-mips64el" element!

AQEMU Warning [9] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-mipsel" element!

AQEMU Warning [10] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-ppc" element!

AQEMU Warning [11] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-ppc64" element!

AQEMU Warning [12] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-ppcemb" element!

AQEMU Warning [13] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-sh4" element!

AQEMU Warning [14] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-sh4eb" element!

AQEMU Warning [15] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-sparc" element!

AQEMU Warning [16] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-sparc64" element!
Segmentation fault (core dumped)
```

here is the output from `qemu-system-x86_64 --version`
```
QEMU emulator version 5.1.0
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
```

googling the errors didn't lead to any solutions. I tried restarting the machine.

**Comment by giorgiga** [comment]
Same behaviour here, running aqemu on manjaro with qemu 5.1.0-3, qt5-base 5.15.1-3, and libvncserver 0.9.13-1.

I'm not 100% sure which version of aqemu I have (I've just installed from AUR): `pacman -Qs aquemu` says `0.9.4-2` but `aquemu --version` says `0.9.3`.

**Comment by drac-dot-gay** [comment]
same issue here, running on arch with the same packages as girogiga

edit: i tried running `aqemu-git`. it actually launched and brought up the setup screen (choose vm directory and find qemu install) but segfaults after that. i think the other package had the same behavior as well

**Comment by adojck** [comment]
I have this same issue. I hope this can get fixed

**Comment by dsiggi** [comment]
Same problem here, running on gentoo.

aqemu: 0.9.2
qemu: 5.2.0-r1

**Comment by manero6** [comment]
same on OpenSuse Tumbleweed with **aqemu** build from source with meson/ninja.

**Comment by Natetronn** [comment]
Started the app from menu, it went through the setup and it found QEMU and that was it. Nothing happened after that.

I get the following from the terminal:

```
❯ aqemu 

AQEMU Warning [2] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-ppcemb" element!
[1]    48486 segmentation fault (core dumped)  aqemu

```
I'm on Manjaro KDE 
Using this package: http://aur.archlinux.org/packages/aqemu
aqemu 0.9.3
qemu 5.2.0

```
❯ qemu-x86_64 --version
qemu-x86_64 version 5.2.0
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
```

**Comment by stevleibelt** [comment]
Same on arch linux

aqemu 0.9.3

qemu-arm --version
qemu-arm version 5.2.0
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers

uname -r
5.11.4-arch1-1

**Comment by mb2g17** [comment]
I get the exact same on manjaro

```
> aqemu
AQEMU Warning [2] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-arm" element!

...

AQEMU Warning [16] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-sparc64" element!
zsh: segmentation fault (core dumped)  aqemu
```

aqemu v0.9.3
qemu v5.2.0

```
> uname -r
5.9.16-1-MANJARO
```

**Comment by 0xf0xx0** [comment]
Bumping, same on EndeavourOS

```
AQEMU Warning [78] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-ppcemb" element!

AQEMU Warning [81] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-ppcemb" element!
[1]    13055 segmentation fault (core dumped)  aqemu
```
```
› qemu-x86_64 --version                                                      ~ 
qemu-x86_64 version 6.0.0
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
› aqemu --version                                                            ~ 
aqemu 0.9.3
```
Kernel `5.14.0-rc5-1-mainline`

**Comment by Bad3r** [comment]
This issue has been discussed in #89 

The sloution mentioned there is manually compiling aqemu after commenting out the section related to "qemu-system-ppcemb"

**Comment by zen2** [comment]
I got the same problem on gentoo.
With commenting out the section related to "qemu-system-ppcemb" and compiling with -j1 that works on an intel platform but not on an amd platform. Intel generated binary works on amd and amd one fails on both amd/intel.
the only difference I can see is dbus with 32/64 bits support on intel and only 64 bits on amd.
Note that if I don't compile with -j1 that don't works and segfault.

If I check with dbus-monitor I can see that segfault happens before dbus call.

**Comment by fuomag9** [comment]
Can still replicate this on aqemu 0.9.4-2 on endeavouros

**Comment by zen2** [comment]
So actual code don't work with qemu >= 3.10.0
Actual upstream version of qemu is 6.1.0.

From this issue, Aqemu segfault actually on:
- gentoo
- arch
- manjaro
- endeavouros
- opensuse

**Comment by ThePademelon** [comment]
I'm experiencing this issue on Void Linux.

**Comment by allhavebrainimplantsandmore** [comment]
Same issue on Arch. Is this a kernel config issue maybe?

**Comment by 0xf0xx0** [comment]
> I got the same problem on gentoo.
> 
> With commenting out the section related to "qemu-system-ppcemb" and compiling with -j1 that works on an intel platform but not on an amd platform. Intel generated binary works on amd and amd one fails on both amd/intel.
> 
> the only difference I can see is dbus with 32/64 bits support on intel and only 64 bits on amd.
> 
> Note that if I don't compile with -j1 that don't works and segfault.
> 
> 
> 
> If I check with dbus-monitor I can see that segfault happens before dbus call.

@allhavebrainimplantsandmore this is the only workaround

**Comment by allhavebrainimplantsandmore** [comment]
> @allhavebrainimplantsandmore this is the only workaround
it didn't work for me

**Comment by lyn1337** [comment]
02/23 problem still persists on Void…

**Comment by ShufflePerson** [comment]
problem still here

```
➜  ~ neofetch
                   -`                    shuffle@archlinux
                  .o+`                   -----------------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: GF65 Thin 10UE REV:1.0
               `+oooooo:                 Kernel: 6.1.10-arch1-1
               -+oooooo+:                Uptime: 1 day, 19 hours, 2 mins
             `/:-:++oooo+:               Packages: 1537 (pacman)
            `/++++/+++++++:              Shell: zsh 5.9
           `/++++++++++++++:             Resolution: 3440x1440
          `/+++ooooooooooooo/`           DE: Plasma 5.26.5
         ./ooosssso++osssssso+`          WM: KWin
        .oossssso-````/ossssss+`         Theme: [Plasma], Breeze [GTK2/3]
       -osssssso.      :ssssssso.        Icons: [Plasma], breeze-dark [GTK2/3]
      :osssssss/        osssso+++.       Terminal: figterm
     /ossssssss/        +ssssooo/-       CPU: Intel i5-10500H (12) @ 4.500GHz
   `/ossssso+/:-        -:/+osssso+-     GPU: Intel CometLake-H GT2 [UHD Graphi
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce RTX 3060 Mobile /
 `++:.                           `-/+/   Memory: 5602MiB / 15815MiB
 .`                                 `/




➜  ~ aqemu

AQEMU Warning [2] >>>
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-ppcemb" element!
[1]    253518 segmentation fault (core dumped)  aqemu
```

**Comment by spillner** [comment]
This is fixed by https://github.com/tobimensch/aqemu/pull/116/commits ; thanks to johna23-lab for cross-linking with the Void Linux ticket that explains it.

**Comment by lineage-of-roots** [comment]
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-ppcemb" element!
Segmentation fault (core dumped

Still the exact same error on Arch

**Comment by lineage-of-roots** [comment]
Nevermind...After getting rid of that, I got it to start, but it still crashes with random segfaults.

I think at this point, aqemu is too old to keep up with the new changes in Qemu and KVM.
